### ISSUE TITLE
Resultado em html

### ISSUE THREAD

**Issue by web1989** [luannsr12/api-correios#1]
Bom dia
Como obter o resultado em html ?

**Comment by luannsr12** [comment]
Beleza! O resultado é em JSON, mas pode utilizar ele para colocar em HTML sim pois é manipulável como objeto. Pode trabalhar com o resultado em JSON em várias linguagens no framework js JQUERY você usaria com JSON.parse(RESULTADO).

Mas caso você não entendeu nada do que eu disse. Você deve procurar um profissional ou apenas estudar e dedicar-se a como enviar este resultado em JSON para HTML
