### ISSUE TITLE
Agradecimento

### ISSUE THREAD

**Issue by pauloalmeidasilva** [luannsr12/api-correios#3]
Olá Luan, muito obrigado. Consegui recuperar aqui os dados. Muito boa sua iniciativa e vou te seguir aqui e no Youtube.

**Comment by luannsr12** [comment]
Opa Paulo! Cara, fico feliz de mais. Obrigado pelo feedback! Se um dia quiser ajudar nessa API, só mandar um Pull Request

**Comment by pauloalmeidasilva** [comment]
Olá Luan, eu fiz algumas mudanças na API. Fiz um Pull Request. Espero que seja útil.
